package com.colormagic.kids.domain.model

// A line-art coloring page generated by the backend. The lifecycle here is:
//   prompt → backend → Sketch → user colors it → SavedPicture
data class Sketch(
    val id: String,
    val prompt: String,
    val imageUrl: String? = null,
    // Falls back to a tinted Box while imageUrl is null / loading.
    val placeholderTint: Long = 0xFFF5F3F8
)
